use Northwind;
GO

CREATE VIEW vw_EmployeePerformance
AS
SELECT
    e.EmployeeID,
    e.FirstName,
    e.LastName,
    e.Title,
    COUNT(DISTINCT o.OrderID) AS TotalOrdersHandled, -- Total number of orders handled by the employee
    SUM(od.Quantity * od.UnitPrice) AS TotalSalesAmount,  -- Total sales amount generated by the employee
    AVG(od.Quantity * od.UnitPrice) AS AverageSalesPerOrder, -- Average sales amount per order
    MIN(o.OrderDate) AS FirstOrderHandled, -- Date of the first order handled by the employee            
    MAX(o.OrderDate) AS LastOrderHandled,  -- Date of the last order handled by the employee            
    CASE
        WHEN MAX(o.OrderDate) >= DATEADD(year, -1, GETDATE()) THEN 'Active'     
        WHEN MAX(o.OrderDate) < DATEADD(year, -1, GETDATE()) 
             AND MAX(o.OrderDate) >= DATEADD(year, -3, GETDATE()) THEN 'Inactive' 
        ELSE 'Lost'                                                        
    END AS EmployeeStatus
GO